# Generated by Django 5.0.6 on 2024-06-11 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference_title', models.CharField(max_length=100)),
                ('conference_description', models.TextField()),
                ('conference_date', models.DateField()),
                ('conference_time', models.TimeField()),
                ('conference_place', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conference Agenda',
                'verbose_name_plural': 'Conference Agenda',
                'db_table': 'conference_agenda',
            },
        ),
        migrations.CreateModel(
            name='ConferenceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference_title', models.CharField(max_length=100)),
                ('conference_description', models.TextField()),
                ('conference_logo', models.ImageField(upload_to='conference_logo')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conference Section',
                'verbose_name_plural': 'Conference Section',
                'db_table': 'conference_section',
            },
        ),
    ]
